name: Build
on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    env:
      CC: gcc-10
      CXX: g++-10
    steps:
      - uses: actions/checkout@v2
      - run: cmake .
      - run: make -j

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: cmake .
      - run: cmake --build .

  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir build && cd build
      - run: cmake .. -DCMAKE_TOOLCHAIN_FILE=../cmake/android.cmake -DSJPEG_ANDROID_NDK_PATH=$ANDROID_NDK_LATEST_HOME
        working-directory: build
      - run: make -j
        working-directory: build
